'use client'

import React from "react";
import "./globals.css";

import {Inter} from "next/font/google";
import type {Metadata} from "next";

import {ApolloClient, ApolloProvider, InMemoryCache} from "@apollo/client";
import {Web3Modal} from "../../../mnft-client/src/context/Web3Modal";

import {Header} from "@/layouts/header";

const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

const client = new ApolloClient({
    uri: 'https://api.studio.thegraph.com/query/477/mnft/v0.0.4',
    cache: new InMemoryCache(),
});

export function ApolloClientProvider({ children }: { children: React.ReactNode }) {
    return (
        <ApolloProvider client={client}>
            {children}
        </ApolloProvider>
    )
}

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <ApolloClientProvider>
                <Web3Modal>
                    <Header />
                    {children}
                </Web3Modal>
            </ApolloClientProvider>
        </body>
        </html>
    );
}
